_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 23
                - 55
            "4": 3.10.9
            "5": 0.18.1
            "8":
                - 1
                - 5
            "9":
                "1": llmapps_intro
            "12": 0.18.1
            "13": darwin-arm64
