_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 2
                - 23
                - 51
                - 55
            "4": 3.8.16
            "5": 0.18.1
            "8":
                - 1
                - 5
            "9":
                "1": llmapps_intro
            "12": 0.18.1
            "13": darwin-arm64
